/* linux/arch/arm/plat-s3c/include/plat/regs-spdif.h
 *
 * Copyright (c) 2003 Simtec Electronics <linux@simtec.co.uk>
 *		      http://www.simtec.co.uk/products/SWLINUX/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * S5PC1XX SPDIF register definition
 */
#ifndef __ASM_ARCH_REGS_SPDIF_H
#define __ASM_ARCH_REGS_SPDIF_H

#include <mach/map.h>

#define S5PC1XX_SPDIF0REG(x)	((x) + S5P_PA_SPDIF)
	
#define S5PC1XX_SPDIF_SPDCLKCON			(0x00)		// Clock control register
#define S5PC1XX_SPDIF_SPDCON			(0x04)		// Control register
#define S5PC1XX_SPDIF_SPDBSTAS			(0x08)		// Burst status register
#define S5PC1XX_SPDIF_SPDCSTAS			(0x0c)		// Channel status register
#define S5PC1XX_SPDIF_SPDDAT			(0x10)		// SPDIFOUT data register
#define S5PC1XX_SPDIF_SPDCNT			(0x14)		// Repetition count register
#define S5PC1XX_SPDIF_SPDBSTAS_SHD		(0x18)		// Shadowed Burst Status Register 
#define S5PC1XX_SPDIF_SPDCNT_SHD		(0x1c)		// Shadowed Repetition count register
#define S5PC1XX_SPDIF_USERBIT1			(0x20)		// Subcode Q1 ~ Q32
#define S5PC1XX_SPDIF_USERBIT2			(0x24)		// Subcode Q33 ~ Q64
#define S5PC1XX_SPDIF_USERBIT3			(0x28)		// Subcode Q65 ~ Q96
#define S5PC1XX_SPDIF_USERBIT1_SHD		(0x2c)		// Shadowed Register Userbit1
#define S5PC1XX_SPDIF_USERBIT2_SHD		(0x30)		// Shadowed Register Userbit2
#define S5PC1XX_SPDIF_USERBIT3_SHD		(0x34)		// Shadowed Register Userbit3
#define S5PC1XX_SPDIF_VERSION_INFO		(0x38)		// RTL version information	


/* Clock control register bit */
#define S5PC1XX_SPDIF_SPDCLKCON_SPDIFOUT_POWER_ON		(1<<0)
#define S5PC1XX_SPDIF_SPDCLKCON_SPDIFOUT_POWER_OFF		(0<<0)

#define S5PC1XX_SPDIF_SPDCLKCON_MAIN_AUDIO_CLK_INT		(0<<2)
#define S5PC1XX_SPDIF_SPDCLKCON_MAIN_AUDIO_CLK_EXT		(1<<2)

/* SPDIFOUT Control Register bit */
#define S5PC1XX_SPDIF_SPDCON_STREAM				(0<<0)
#define S5PC1XX_SPDIF_SPDCON_PCM				(1<<0)

#define S5PC1XX_SPDIF_SPDCON_PCM_DATA_SIZE_16			(0<<1)
#define S5PC1XX_SPDIF_SPDCON_PCM_DATA_SIZE_20			(1<<1)
#define S5PC1XX_SPDIF_SPDCON_PCM_DATA_SIZE_24			(2<<1)

#define S5PC1XX_SPDIF_SPDCON_MAIN_AUDIO_CLK_FREQ_256		(0<<3)
#define S5PC1XX_SPDIF_SPDCON_MAIN_AUDIO_CLK_FREQ_384		(1<<3)
#define S5PC1XX_SPDIF_SPDCON_MAIN_AUDIO_CLK_FREQ_512		(2<<3)

#define S5PC1XX_SPDIF_SPDCON_SOFTWARE_RESET_NO			(0<<5)
#define S5PC1XX_SPDIF_SPDCON_SOFTWARE_RESET_EN			(1<<5)

#define S5PC1XX_SPDIF_SPDCON_STREAM_END_INT_ENABLE		(1<<6)
#define S5PC1XX_SPDIF_SPDCON_STREAM_END_INT_MASKED		(0<<6)
#define S5PC1XX_SPDIF_SPDCON_STREAM_END_INT_STATUS_PENDING	(1<<7)
#define S5PC1XX_SPDIF_SPDCON_STREAM_END_INT_STATUS_NO_PENDING	(0<<7)


#define S5PC1XX_SPDIF_SPDCON_BUFFER_EMPTY_INT_ENABLE		(1<<8)
#define S5PC1XX_SPDIF_SPDCON_BUFFER_EMPTY_INT_MASKED		(0<<8)
#define S5PC1XX_SPDIF_SPDCON_BUFFER_EMPTY_INT_STATUS_PENDING	(1<<9)
#define S5PC1XX_SPDIF_SPDCON_BUFFER_EMPTY_INT_STATUS_NO_PENDING	(0<<9)

#define S5PC1XX_SPDIF_SPDCON_USER_DATA_INT_ENABLE		(1<<10)
#define S5PC1XX_SPDIF_SPDCON_USER_DATA_INT_MASKED		(0<<10)
#define S5PC1XX_SPDIF_SPDCON_USER_DATA_INT_STATUS_PENDING	(1<<11)
#define S5PC1XX_SPDIF_SPDCON_USER_DATA_INT_STATUS_NO_PENDING	(0<<11)

#define S5PC1XX_SPDIF_SPDCON_USER_DATA_ATTACH_USERBIT		(0<<12)
#define S5PC1XX_SPDIF_SPDCON_USER_DATA_ATTACH_AUDIO_DATA	(1<<12)

#define S5PC1XX_SPDIF_SPDCON_ENDIAN_FORMAT_BIG			(0<<13)
#define S5PC1XX_SPDIF_SPDCON_ENDIAN_FORMAT_4BYTE_SWAP		(1<<13)
#define S5PC1XX_SPDIF_SPDCON_ENDIAN_FORMAT_3BYTE_SWAP		(2<<13)
#define S5PC1XX_SPDIF_SPDCON_ENDIAN_FORMAT_2BYTE_SWAP		(3<<13)

#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_INT_ENABLE		(1<<15)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_INT_MASKED		(0<<15)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_INT_STATUS_PENDING	(1<<16)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_INT_STATUS_NO_PENDING	(0<<16)

#define S5PC1XX_SPDIF_SPDCON_FIFO_TRANSFER_MODE_DMA		(0<<17)
#define S5PC1XX_SPDIF_SPDCON_FIFO_TRANSFER_MODE_POL		(1<<17)
#define S5PC1XX_SPDIF_SPDCON_FIFO_TRANSFER_MODE_INT		(2<<17)

#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_0		(0<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_1		(1<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_2		(2<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_3		(3<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_4		(4<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_5		(5<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_6		(6<<19)
#define S5PC1XX_SPDIF_SPDCON_FIFO_LEVEL_THRESHOLD_7		(7<<19)


/* SPDIFOUT Burst Status Register bit */
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_NULL	(0<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_AC3		(1<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_PAUSE	(3<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_MPEG1_L1	(4<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_MPEG1_L23	(5<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_MPEG2	(6<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_MPEG2_L1	(8<<0)
#define S5PC1XX_SPDIF_SPDBSTAS_COMPRESSED_DATA_TYPE_MPEG2_L23	(9<<0)

#define S5PC1XX_SPDIF_SPDBSTAS_ERROR_FLAG_VALID			(0<<7)
#define S5PC1XX_SPDIF_SPDBSTAS_ERROR_FLAG_ERROR			(1<<7)

#define S5PC1XX_SPDIF_SPDBSTAS_DATA_TYPE_DEP_INFO		(0<<8)

#define S5PC1XX_SPDIF_SPDBSTAS_BITSTREAM_NUMBER(X)		((X)<<13)
#define S5PC1XX_SPDIF_SPDBSTAS_BURST_DATA_LENGTH(X)		(((X)*16)<<16)

/* SPDIFOUT Channel Status Register bit */
#define S5PC1XX_SPDIF_SPDCSTAS_CHANNEL_STATUS_BLOCK_CON		(0<<0)
#define S5PC1XX_SPDIF_SPDCSTAS_CHANNEL_STATUS_BLOCK_PRO		(1<<0)

#define S5PC1XX_SPDIF_SPDCSTAS_AUDIO_SAMPLE_WORD_LINEAR_PCM	(0<<1)
#define S5PC1XX_SPDIF_SPDCSTAS_AUDIO_SAMPLE_WORD_NON_LINEAR_PCM	(1<<1)

#define S5PC1XX_SPDIF_SPDCSTAS_COPYRIGHT_ASSERTION		(0<<2)
#define S5PC1XX_SPDIF_SPDCSTAS_COPYRIGHT_ASSERTION_NO		(1<<2)

#define S5PC1XX_SPDIF_SPDCSTAS_EMPHASIS_WITHOUT_PRE_EMP		(0<<3)
#define S5PC1XX_SPDIF_SPDCSTAS_EMPHASIS_WITH_PRE_EMP		(1<<3)

#define S5PC1XX_SPDIF_SPDCSTAS_CHANNEL_SATAUS_MODE		(0<<6)

#define S5PC1XX_SPDIF_SPDCSTAS_CATEGORY_CODE_CD			(1<<8)

#define S5PC1XX_SPDIF_SPDCSTAS_SOURCE_NUMBER(X)			((X)<<16)

#define S5PC1XX_SPDIF_SPDCSTAS_CHANNEL_NUMBER(X)		((X)<<20)

#define S5PC1XX_SPDIF_SPDCSTAS_SAMPLING_FREQ_44_1		(0<<24)
#define S5PC1XX_SPDIF_SPDCSTAS_SAMPLING_FREQ_48			(2<<24)
#define S5PC1XX_SPDIF_SPDCSTAS_SAMPLING_FREQ_32			(3<<24)
#define S5PC1XX_SPDIF_SPDCSTAS_SAMPLING_FREQ_96			(10<<24)

#define S5PC1XX_SPDIF_SPDCSTAS_CLOCK_ACCURACY_50		(2<<28)
#define S5PC1XX_SPDIF_SPDCSTAS_CLOCK_ACCURACY_1000		(0<<28)
#define S5PC1XX_SPDIF_SPDCSTAS_CLOCK_ACCURACY_VARIABLE		(1<<28)

/* SPDIFOUT Repetition Count Register bit */
#define S5PC1XX_SPDIF_SPDCNT_STREAM_REPETITION_COUNT(X)		(((X)*2)<<0)







































































#endif //__ASM_ARCH_REGS_SPDIF_H

