# S5PC1XX Platform Support
snd-soc-s5pc1xx-objs := s5pc1xx-pcm.o
snd-soc-s5pc1xx-i2s-v50-objs := s5pc100-i2s-v50.o
snd-soc-s5pc1xx-ac97-objs := s5pc1xx-ac97.o
snd-soc-s5pc1xx-spdif-objs := s5pc100-spdif.o

obj-$(CONFIG_SND_S5PC1XX_SOC) += snd-soc-s5pc1xx.o
obj-$(CONFIG_SND_SOC_I2S_V50) += snd-soc-s5pc1xx-i2s-v50.o
obj-$(CONFIG_SND_S5PC100_SOC_AC97) += snd-soc-s5pc1xx-ac97.o
obj-$(CONFIG_SND_S5PC100_SOC_SPDIF) += snd-soc-s5pc1xx-spdif.o

# S5PC1XX Machine Support
snd-soc-smdkc1xx-wm8580-objs := smdkc100_wm8580.o
snd-soc-smdkc1xx-wm9713-objs := smdkc100_wm9713.o
snd-soc-smdkc1xx-spdif-objs := smdkc100_spdif.o

obj-$(CONFIG_SND_SMDKC100_WM8580) += snd-soc-smdkc1xx-wm8580.o
obj-$(CONFIG_SND_SMDKC100_WM9713) += snd-soc-smdkc1xx-wm9713.o
obj-$(CONFIG_SND_SMDKC100_SPDIF) += snd-soc-smdkc1xx-spdif.o
